<?php 
return [
    'lang' => 'VIETNAM',
    'topNav' => [
        'nav1' => 'Ưu thích',
        'nav2' => 'Thanh toán',
        'nav3' => 'Giỏ hàng',
        'nav4' => 'Thông tin cá nhân',
        'nav5' => 'Hoá đơn',
        'nav6' => 'Đổi mật khẩu',
        'nav7' => 'Đăng xuất',
        'nav8' => 'Đăng nhập',
        'nav9' => 'Đăng ký'
    ],
    'menu' => [
        'menu1' => 'Trang chủ',
        'menu2' => 'Cửa hàng',
        'menu3' => 'Sản phẩm',
        'menu4' => 'Chi tiết sản phẩm',
        'menu5' => 'Thanh toán',
        'menu6' => 'Giỏ hàng',
        'menu7' => 'Đăng nhập',
        'menu8' => 'Bài viết',
        'menu9' => 'Danh sách bài viết',
        'menu10' => 'Chi tiết bài viết',
        'menu11' => 'Liên hệ',
        'menu12' => 'Tìm kiếm theo tên ....'
    ],
    'footer' => [
        'footer1' => 'Hỗ trợ',
        'footer2' => 'Trợ giúp online',
        'footer3' => 'Liên hệ',
        'footer4' => 'Trạng thái hoá đơn',
        'footer5' => 'Thay đổi vị trí',
        'footer6' => 'Hỏi đáp',
        'footer7' => 'Cửa hàng',
        'footer8' => 'Áo',
        'footer9' => 'Đàn ông',
        'footer10' => 'Phụ nữ',
        'footer11' => 'Thẻ quà tặng',
        'footer12' => 'Giày',
        'footer13' => 'Chính sách',
        'footer14' => 'Điều khoản sử dụng',
        'footer15' => 'Chính sách bảo mật',
        'footer16' => 'Chính sách hoàn lại tiền',
        'footer17' => 'Hệ thống thanh toán',
        'footer18' => 'Về hệ thống',
        'footer19' => 'Về shopper',
        'footer20' => 'Thông tin công ty',
        'footer21' => 'Nghề nghiệp',
        'footer22' => 'Ví trí cửa hàng',
        'footer23' => 'Chương trình liên kết',
        'footer24' => 'Copyright',
        'footer25' => 'Nhập địa chỉ email của bạn',
        'footer26' => 'Nhận các bản cập nhật gần đây nhất từ <br>
        trang web của chúng tôi và được cập nhật bản thân của bạn ...'
    ],
    'banner' => [
        'banner1' => 'Cửa hàng mua sắm trực tuyến thả ga',
        'banner2' => 'Bạn sẽ có mọi thứ mà bạn mong muốn nếu như bạn diện đồ vì chúng.',
        'banner3' => 'Cửa hàng mua sắm trực tuyến thả ga',
        'banner4' => 'Phong cách là một phương thức để nói lên bạn là ai mà không khiến bạn tốn một lời.',
        'banner5' => 'Không chỉ còn là trang phục, đó là Life Style',
        'banner6' => 'Cung cấp những mặc hàng tốt nhất, chất lượng nhất đến với mọi người.',
        'button' => 'Mua ngay'
    ],
    'title' => [
        'category' => 'Danh mục',
        'product' => 'Sản phẩm',
        'Recommend' => 'Sản phẩm được đề xuất',
        'newProduct' => 'Sản phẩm mới',
        'topSale'   => 'Sản phẩm bán chạy',
        'button' => 'Xem chi tiết',
        'brand' => 'Thương hiệu',
        'search_price' => 'Chọn khoảng giá'
    ],
    'cart' => [
        'cart1' => 'Giỏ hàng đang trống',
        'cart2' => 'Tiếp tục mua hàng',
        'cart3' => 'Giỏ hàng hiện tại của bạn đang rỗng, vui lòng thêm sản phẩm',
        'cart4' => 'Tiếp tục mua hàng',
        'cart5' => 'Ảnh',
        'cart6' => 'Tên',
        'cart7' => 'Số lượng',
        'cart8' => 'Giá',
        'cart9' => 'Thành tiền',
        'cart10' => 'Cập nhật',
        'cart11' => 'Số lượng',
        'cart12' => 'Tổng tiền',
        'cart13' => 'Tiếp tục mua hàng',
        'cart14' => 'Thanh toán',
        'cart15' => 'Xoá giỏ hàng',
        'cart16' => 'Ngày đặt',
        'cart17' => 'Trạng thái',
        'cart18' => 'Chưa xác nhận',
        'cart19' => 'Đã xác nhận',
        'cart20' => 'Đã giao hàng/ Thanh toán',
        'cart21' => 'Đã huỷ',
        'cart22' => 'Thông tin chi tiết sản phẩm'
    ],
    'checkout' => [
        'checkout1' => 'Thông tin tài khoản',
        'checkout2' => 'Tên',
        'checkout3' => 'Email',
        'checkout4' => 'Số điện thoại',
        'checkout5' => 'Địa chỉ',
        'checkout6' => 'Thông tin nhận hàng',
        'checkout7' => 'Lời nhắn',
        'checkout8' => 'Đặt hàng',
        'checkout9' => 'Xác nhận đơn hàng thành công'
    ],
    'order' => [
        'order1' => 'Chi tiết đơn hàng online',
        'order2' => 'Thông tin khách hàng',
        'order3' => 'Họ và tên',
        'order4' => 'Email',
        'order5' => 'Điện thoại',
        'order6' => 'Địa chỉ',
        'order7' => 'Thông tin người nhận',
        'order8' => 'Thông tin chi tiết đơn hàng',
        'order9' => 'Quản lí đơn hàng'
    ],
    'status' => [
        'status1' => 'Đặt hàng thành công',
        'status2' => 'Vui lòng kiểm tra hộp thư của mail và xác nhận đơn hàng. Hệ thống sẽ tự hủy đơn hàng nếu trong vòng 24h bạn
        không xác nhận đơn hàng này',
        'status3' => 'Mở email của bạn'
    ],
    'product' => [
        'product1' => 'Hết hàng',
        'product2' => 'Thêm vào giò hàng',
        'product3' => 'Khả dụng',
        'product4' => 'Trong kho',
        'product5' => 'Tình trạng',
        'product6' => 'Mới',
        'product7' => 'Thương hiệu',
        'product8' => 'Chi tiết',
        'product9' => 'Hồ sơ công ty',
        'product10' => 'Đánh giá',
        'product11' => 'Bình luận sản phẩm này',
        'product12' => 'Nội dung bình luận',
        'product13' => 'Gửi bình luận',
        'product14' => 'Vui lòng đăng nhập để bình luận'
    ]
];
?>